create table temp_participant as select participant_id from participant_assignments where study_site_id in (select id from study_organizations where study_id = -1);
create table temp_participant_assignment as select id from participant_assignments where study_site_id in (select id from study_organizations where study_id = -1);
delete from labs where assignment_id in (select id from temp_participant_assignment);
delete from spa_concomitant_medications where assignment_id in (select id from temp_participant_assignment);
delete from spa_metastatic_disease_sites where spa_disease_history_id in (select id from spa_disease_histories where assignment_id in (select id from temp_participant_assignment));
delete from spa_disease_histories where assignment_id in (select id from temp_participant_assignment);
delete from spa_pre_existing_conds where assignment_id in (select id from temp_participant_assignment);
delete from spa_prior_therapy_agents where spa_prior_therapy_id in (select id from spa_prior_therapies where assignment_id in (select id from temp_participant_assignment));
delete from spa_prior_therapies where assignment_id in (select id from temp_participant_assignment);
delete from participants where id in (select id from temp_participant);
delete from identifiers where participant_id in (select id from temp_participant);
delete from participant_assignments where id in (select id from temp_participant_assignment);
delete from terminologies where study_id = -1;
delete from study_investigators where id = -1;
delete from study_organizations where id IN (-1,-2,-3);
delete from site_investigators where id = -1;
delete from investigators where id = -1;
delete from epochs where id IN (-1,-2,-3);
delete from disease_terminologies where study_id = -1;
delete from identifiers where stu_id = -1;
delete from studies where id = -1;
drop table temp_participant;
drop table temp_participant_assignment;